server:
  port: 8080
spring:
  application:
    name: "social"
  datasource:
    username: "sa"
    password: ""
    url: "jdbc:postgresql://db:5432/postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none